[build]
target = ["x86_64-unknown-none"]
code-model = ["kernel"]
rustflags = ["-C", "link-args=--entry KernelMain --image-base 0x100000 --static"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
