[build]
# target = "x86_64-unknown-none"
target = "x86_64-unknown-none-os.json"
# rustflags = ["-Crelocation-model=static", "-Clink-args=-okernel.elf"]

# [profile.dev]
# panic = "abort"

# [profile.dev]
# panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
