[build]
# target = ["x86_64-unknown-none"]
# rustflags = ["-C", "link-args=--entry _kernel_main -z norelro --image-base 0x100000 --static -okernel.elf"]
target = "x86_64-unknown-none-os.json"

# [profile.dev]
# panic = "abort"

# [profile.dev]
# panic = "abort"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
